### ISSUE TITLE
Crash on launch  - run.sh line 22 - illegal instruction 

### ISSUE THREAD

**Issue by mbfrydman** [wendevlin/homeassistant-addons#8] opened 2024-08-19 06:44 UTC
`successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
/config/homedocs is not empty, skipping copy example content.
/run.sh: line 22:    85 Illegal instruction     (core dumped) DOCS_BASE_PATH=/config/homedocs bun run start:production
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

Same behavior in the first launch than subsequent.

Tried deleting home folder, creation goes through properly.

This is on latest HA running on NUC with HACS installed but low customization.

**Comment by wendevlin** [comment] 2024-08-19 11:31
I will try to reproduce. Maybe an issue when running on amd64 chip. I was just testing on my home assitant blue. When I have time I will try it out on my notebook.

**Comment by mbfrydman** [comment] 2024-08-19 12:01
Great, willing to test if needed.
For me this is running on a vM in proxmox using the helper scripts install.

**Comment by wendevlin** [comment] 2024-08-21 06:46
> Great, willing to test if needed.
> 
> For me this is running on a vM in proxmox using the helper scripts install. 

I installed it via virtual box on my machine and there was no issue. 

Do you use home assistant OS?

**Comment by mbfrydman** [comment] 2024-08-21 07:02
Home assistant os installed on prox through this script : https://tteck.github.io/Proxmox/

Standard install
2 sockets
4gb ram
Ovmf bios

**Comment by wendevlin** [comment] 2024-08-21 07:10
Can you check if you see any error logs in your supervisor logs? /config/logs?provider=supervisor

**Comment by mbfrydman** [comment] 2024-08-21 07:16
Supervisor logs seem clean : 
`[supervisor.docker.addon] Starting Docker add-on ghcr.io/wendevlin/amd64-addon-homedocs with version 2.0.4
2024-08-21 09:12:53.484 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Homedocs is failed, restarting...
2024-08-21 09:12:53.489 INFO (SyncWorker_0) [supervisor.docker.manager] Cleaning addon_f61269d7_homedocs application
2024-08-21 09:12:53.871 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/wendevlin/amd64-addon-homedocs with version 2.0.4
2024-08-21 09:12:57.427 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Homedocs is failed, restarting...
2024-08-21 09:12:57.434 INFO (SyncWorker_5) `

Nothing else in the logs seem relevant

**Comment by wendevlin** [comment] 2024-08-21 07:17
ok thanks. So the only error we have is: 
`/run.sh: line 22:    85 Illegal instruction     (core dumped) DOCS_BASE_PATH=/config/homedocs bun run start:production`

**Comment by wendevlin** [comment] 2024-08-21 07:20
I assume it is bun related with your architecture. I will upgrade bun to newest version and then we will try again.

**Comment by mbfrydman** [comment] 2024-08-21 07:23
Great, thanks.
Googling the error point in that direction. 

I would think my use case nuc - > prox-> HAos is common.

**Comment by wendevlin** [comment] 2024-08-21 09:27
Please update to version [2.0.6](https://github.com/wendevlin/homeassistant-addons/commit/790fc8a6fc53ce37efb4496353cc6e99c3e8d226). I changed the base image to debian and use now the latest bun version.

**Comment by mbfrydman** [comment] 2024-08-21 09:32
Just tested, error changed but is likely the same cause : 

`s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
/config/homedocs is not empty, skipping copy example content.
/run.sh: line 22:    85 Illegal instruction     (core dumped) DOCS_BASE_PATH=/config/homedocs ~/.bun/bin/bun run start:production
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by wendevlin** [comment] 2024-08-21 10:37
:cry:  can you tell me which CPU the NUC has?

**Comment by mbfrydman** [comment] 2024-08-21 10:50
4x Intel celeron N5105
Running latest prox and up to date.

**Comment by wendevlin** [comment] 2024-08-21 11:34
ok thanks. It seems to be a bun issue with the CPU. I will migrate to nodejs and ping you when it's ready

**Comment by wendevlin** [comment] 2024-08-23 13:54
@mbfrydman Hi, I migrated to nodejs.
It is now in the beta repository. 
You can check it out when you add to your addonstore this repo: https://github.com/wendevlin/homeassistant-addons#beta
Then you get a Homedocs (Beta) addon in your store, install and start it.

I hope it works now on your NUC :slightly_smiling_face:  When it works I will then move it to the production branch.

**Comment by mbfrydman** [comment] 2024-08-23 14:33
Working. Can be marked as fixed.
Congrats on closing the first issue :)

**Comment by wendevlin** [comment] 2024-08-23 14:55
> Working. Can be marked as fixed.
> 
> Congrats on closing the first issue :)

Awesome thank you. I keep it open till it is merged the main branch.

**Closed** 2024-08-26 08:12 UTC
Labels: bug
